### ISSUE TITLE
Simulator console window context menu disable.

### ISSUE THREAD

**Issue by RogerDoering** [mipsym/MIPSym-issues#5]
**Is your feature request related to a problem? Please describe.**
whenever you right-click on the console, a context menu pops up. For some applications it would be nice to disable this feature.

**Describe the solution you'd like**
Perhaps add a setting to allow the user to disable.

**Describe alternatives you've considered**
none viable

**Additional context**
![image](https://user-images.githubusercontent.com/84110188/118064844-ae6bfb80-b350-11eb-8cf8-b43c2c745624.png)

**Comment by ddalcino** [comment]
I have implemented a fix for this in the main branch; it will go out in the next release. To use it, toggle the checkbox at **'Settings > Console context menu on right-click'**.

I am not quite satisfied with the name "Console context menu on right-click". I'm not sure how to make the meaning more explicit without making the name really long. Perhaps it could be "Enable context menu in console"?

**Comment by ddalcino** [comment]
Fixed in 2.05.1520
